name: Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: make install

      - name: Run tests on the main Python file
        run: make test
      
      - name: Generate reports on the run
        run: make generate